[tasks.test]
description = "Nightly is required for --all-features b/c it uses benchmarking"
args = ["test"]

[tasks.benchmark]
condition = { channels = ["nightly"] }
command = "cargo"
args = ["test", "--all-features"]

[tasks.readme]
install_crate = "cargo-readme"
command = "cargo"
args = ["readme", "-o", "README.md"]

[tasks.doc-katex]
env = { "RUSTDOCFLAGS" = "--html-in-header katex-header.html" }
command = "cargo"
args = ["doc", "--no-deps"]

[tasks.doc-all]
dependencies = [
    "docs",
    "doc-katex",
]

[tasks.all]
dependencies = [
    "test",
    "benchmark",
    "clippy",
    "format",
    "readme",
    "doc-all",
]
